// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://srvvqtlawmnhdddlffuf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNydnZxdGxhd21uaGRkZGxmZnVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MDQxNTQsImV4cCI6MjA2NjI4MDE1NH0.CzfhSZc8JTcIvdUEX8rALnWWD8RdTsy2kVkHAxcWr38";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);